<!DOCTYPE html>
<html lang="fr">
    <?php include './templates/blocs/head.phtml' ?>
<body>
    <header id="entete">
        <?php include './templates/blocs/nav.phtml' ?>
        <div id="titre" class="container d-flex justify-content-between flex-column align-items-center">
            <h1 class="roboto black">DES ENCAS SAINS POUR LA JOURNÉE</h1>
            <h2 class="rockwell">Des produits sains à base de blé bio à grignoter pendant la journée 😀🌽</h2>
            <a class="shadow" href="#concept">Découvrir</a>
        </div>
    </header>


    <section id="concept" class="container">
        <div class="row">
            <header class="col-md-4 col-sm-12">
                <h2>Du naturel<br>au goûter ?</h2>
            </header>
            <div class="col-md-8 col-sm-12 row">
                <article class="col-md-6 col-sm-12">
                    <img src="img/organic-2.png" alt="naturel">
                    <h3>Du naturel</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla maximus lacus ante, in mattis dui
                        auctor vel. Etiam elit nisl, aliquam sed accusant fringilla, bibendum non dolor. </p>
                </article>
                <article class="col-md-6 col-sm-12">
                    <img src="img/organic-1.png" alt="bio">
                    <h3>Exploitation bio</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla maximus lacus ante, in mattis dui
                        auctor vel. Etiam elit nisl, aliquam sed accusant fringilla, bibendum non dolor. </p>
                </article>
                <article class="col-md-6 col-sm-12">
                    <img src="img/detox.png" alt="sain">
                    <h3>Un encas sain</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla maximus lacus ante, in mattis dui
                        auctor vel. Etiam elit nisl, aliquam sed accusant fringilla, bibendum non dolor. </p>
                </article>
                <article class="col-md-6 col-sm-12">
                    <img src="img/grain-1.png" alt="light">
                    <h3>Faible en calories</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla maximus lacus ante, in mattis dui
                        auctor vel. Etiam elit nisl, aliquam sed accusant fringilla, bibendum non dolor. </p>
                </article>
            </div>
        </div>
    </section>

    <section id="produits" class="container shadow">
        <h2>Produits à découvrir</h2>
        <ul class="row">
            <li class="col-md-4 col-sm-12">
                <img src="img/Image 1.png" alt="">
                <h3>Barre protéinée</h3>
                <span class="rockwell">1,05€</span>
            </li>
            <li class="col-md-4 col-sm-12">
                <img src="img/Image 2.png" alt="">
                <h3>Pâte à tartiner</h3>
                <span class="rockwell">5,49€</span>
            </li>
            <li class="col-md-4 col-sm-12">
                <img src="img/Image 3.png" alt="">
                <h3>Thé détox</h3>
                <span class="rockwell">14,50€</span>
            </li>
        </ul>
    </section>


    <?php include './templates/blocs/footer.phtml' ?>

</body>

</html>