<!DOCTYPE html>
<html lang="fr">
    <?php include './templates/blocs/head.phtml' ?>
<body>
    <header id="entete">
        <?php include './templates/blocs/nav.phtml' ?>
        <div id="titre" class="shorter container d-flex justify-content-between flex-column align-items-center">
            <h1 class="roboto black">NOS PRODUITS</h1>
            <h2 class="rockwell">Des produits sains à base de blé bio à grignoter pendant la journée 😀🌽</h2>
        </div>
    </header>

    <section id="featured" class="container">
        <h2>Nos produits phares</h2>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="img/granola.jpg" alt="granola">
                    <div class="carousel-caption">
                        <h3>Granola</h3>
                        <p>Un granola d'exception gourmand allégé en sucres</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="img/latte.jpg" alt="latte">
                    <div class="carousel-caption ">
                        <h3>Latte au blé</h3>
                        <p>Profitez d'une pause gourmande sans culpabilité</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="img/juice.jpg" alt="juice">
                    <div class="carousel-caption">
                        <h3>Des jus détox</h3>
                        <p>Des petites bouteilles de jus à emporter avec vous partout !</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </section>

    <section id="produits" class="container">
        <h2>Le reste des produits</h2>
        <ul class="row">

            <?php foreach($products as $id => $product) : ?>
            <li class="col-md-4 col-sm-12">
                <a href="produit.php?id=<?=$id?>">
                    <img src="img/products/<?=$product['image']?>" alt="">
                    <h3><?=$product['name']?></h3>
                    <span class="rockwell"><?=number_format($product['price'], 2, ',', ' ')?>€</span>
                </a>
            </li>
            <?php endforeach; ?>

        </ul>
    </section>

    <?php include './templates/blocs/footer.phtml' ?>

</body>

</html>