<footer id="contact">
        <div class="container ">
            <div class="row">
                <aside class="col-md-5 col-sm-12">
                    <h2>Nous contacter</h2>
                    <div id="email">
                        <div class="d-flex align-items-center">
                            <img src="img/mail.png" alt="contact">
                            <span id="sep"></span>
                            <img src="img/pin-3.png" alt="">
                        </div>
                    </div>
                    <p id="adresse">35 rue Marengo<br>13006 Marseille</p>
                    <ul class="d-flex justify-content-center">
                        <li><a href="#"><img src="img/logo-facebook.png" alt=""></a></li>
                        <li class="mx-4"><a href="#"><img src="img/logo-instagram.png" alt=""></a></li>
                        <li><a href="#"><img src="img/logo-messenger.png" alt=""></a></li>
                    </ul>
                </aside>
                <form action="" class="col-md-7 col-sm-12 d-flex flex-column justify-content-center align-items-center">
                    <input type="text" placeholder="Nom">
                    <input type="text" placeholder="Email">
                    <textarea name="" id="" cols="30" rows="10" placeholder="Message"></textarea>
                    <button type="submit" class="bouton shadow">Envoyer</button>
                </form>
            </div>
            <div class="footer row flex-column justify-content-center align-items-center mt-4">
                <p>2019 © Cornfood - by La Passerelle</p>
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>