<div id="nav" class="container d-flex justify-content-between align-items-center">
    <img src="img/logo.png" alt="logo">
    <nav id="bt-menu" class="bt-menu">
        <a class="bt-menu-trigger"><span>Menu</span></a>
        <ul class="d-md-inline-flex d-sm-flex flex-sm-column flex-md-row roboto black">
            <li><a href="index.php">Home</a></li>
            <li><a href="index.php#concept">Concept</a></li>
            <li><a href="produits.php">Produits</a></li>
            <li><a href="index.php#contact">Contact</a></li>
        </ul>
    </nav>
</div>